name: example
description: An example project showcasing the functionality of Mockingjay.
version: 0.0.1
homepage: https://github.com/VeryGoodOpenSource/mockingjay

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  universal_io: ^2.2.2

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mockingjay:
    path: ../
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
