name: mockingjay
description: A package that makes it easy to mock, test and verify navigation calls in Flutter.
version: 1.0.0
homepage: https://github.com/VeryGoodOpenSource/mockingjay

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  matcher: ^0.12.16+1
  mocktail: ^1.0.4
  test: ^1.25.7

dev_dependencies:
  very_good_analysis: ^6.0.0
