name: mockingjay
description: A package that makes it easy to mock, test and verify navigation calls in Flutter.
version: 2.1.0
homepage: https://github.com/VeryGoodOpenSource/mockingjay

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  matcher: ^0.12.17
  mocktail: ^1.0.4
  test: ^1.26.3

dev_dependencies:
  very_good_analysis: ^10.0.0
