name: mock_navigator
description: An experimental package that attempts to make it easy to mock
  Flutter's navigator routes.
version: 0.0.1
homepage: https://github.com/jeroen-meijer/mock_navigator

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  coverage: 1.0.2
  mockito: 5.0.5
  mocktail: 0.1.1
  very_good_analysis: 2.0.3
